
spring:
  application:
    name: restaurant-api
  jackson:
    default-property-inclusion: non-null
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: ${DB_HOST}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 60000
      idle-timeout: 30000
      connection-timeout: 30000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
logging:
  level:
    "[org.hibernate.sql]": debug
security:
  jwt:
    user: ${JWT_USER}
    secret-key: ${JWT_SECRET_KEY}
    expiration: 86400000
    refresh-token:
      expiration: 604800000
debug: true